"use client"

import { useState } from "react"
import { Button } from "@/components/ui/Button"

type ApiResponse<T> = {
  ok?: boolean
  data?: T
  error?: { message?: string }
}

type ToolResultProps = {
  title: string
  result: unknown
}

function ResultPanel({ title, result }: ToolResultProps) {
  if (!result) {
    return (
      <div className="bg-surface-container-low border border-outline-variant/30 rounded-xl shadow-sm p-stack-md flex flex-col justify-center min-h-[320px]">
        <h3 className="font-headline-md text-headline-md font-semibold text-primary">Results Preview</h3>
        <p className="font-body-sm text-body-sm text-on-surface-variant mt-2">
          Run the tool to see a production result generated by the backend.
        </p>
      </div>
    )
  }

  return (
    <div className="bg-surface-container-low border border-outline-variant/30 rounded-xl shadow-sm p-stack-md min-h-[320px]">
      <div className="flex justify-between items-center mb-stack-md">
        <h3 className="font-headline-md text-headline-md font-semibold text-primary">{title}</h3>
        <span className="bg-surface-container-lowest border border-outline-variant/30 px-2 py-1 rounded text-body-sm font-body-sm text-on-surface-variant">
          Live Result
        </span>
      </div>
      <pre className="whitespace-pre-wrap break-words text-body-sm font-mono text-primary bg-surface-container-lowest border border-outline-variant/20 rounded-lg p-3 max-h-[520px] overflow-auto">
        {JSON.stringify(result, null, 2)}
      </pre>
    </div>
  )
}

function useTool<T>() {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")
  const [result, setResult] = useState<T | null>(null)

  async function post(endpoint: string, payload: Record<string, unknown>) {
    setLoading(true)
    setError("")

    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      })
      const json = (await response.json()) as ApiResponse<{ result: T }>

      if (!response.ok || !json.ok || !json.data) {
        throw new Error(json.error?.message ?? "Unable to run tool.")
      }

      setResult(json.data.result)
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "Unable to run tool.")
    } finally {
      setLoading(false)
    }
  }

  return { loading, error, result, post }
}

export function AtsScoreTool() {
  const [resumeText, setResumeText] = useState("")
  const [targetRole, setTargetRole] = useState("")
  const tool = useTool<Record<string, unknown>>()

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-gutter">
      <form
        className="lg:col-span-7 bg-surface-container-lowest border border-outline-variant/30 rounded-xl shadow-sm p-stack-md flex flex-col gap-stack-md"
        onSubmit={(event) => {
          event.preventDefault()
          tool.post("/api/tools/ats-score", { resumeText, targetRole })
        }}
      >
        <textarea
          className="w-full min-h-[260px] bg-background border border-outline-variant/50 rounded p-stack-sm font-body-sm text-body-sm text-on-surface resize-y placeholder:text-surface-tint outline-none focus:border-secondary"
          placeholder="Paste your resume text here..."
          value={resumeText}
          onChange={(event) => setResumeText(event.target.value)}
          required
        />
        <input
          className="w-full bg-background border border-outline-variant/50 rounded px-3 py-2 text-body-sm outline-none focus:border-secondary"
          placeholder="Target job title (optional)"
          value={targetRole}
          onChange={(event) => setTargetRole(event.target.value)}
        />
        {tool.error && <p className="text-body-sm text-error">{tool.error}</p>}
        <Button size="lg" className="w-full gap-2 text-base" disabled={tool.loading}>
          <span className="material-symbols-outlined">analytics</span>
          {tool.loading ? "Checking..." : "Check My Resume Score"}
        </Button>
      </form>
      <div className="lg:col-span-5">
        <ResultPanel title="ATS Score" result={tool.result} />
      </div>
    </div>
  )
}

export function ResumeMatchTool() {
  const [resumeText, setResumeText] = useState("")
  const [jobDescriptionText, setJobDescriptionText] = useState("")
  const tool = useTool<Record<string, unknown>>()

  return (
    <>
      <form
        className="grid grid-cols-1 lg:grid-cols-2 gap-gutter mb-stack-lg"
        onSubmit={(event) => {
          event.preventDefault()
          tool.post("/api/tools/resume-match", { resumeText, jobDescriptionText })
        }}
      >
        <div className="bg-surface-container-lowest border border-outline-variant rounded-lg p-stack-md shadow-sm flex flex-col h-full">
          <h2 className="font-label-uppercase text-label-uppercase text-primary mb-stack-sm">Your Resume</h2>
          <textarea className="w-full flex-grow min-h-[300px] bg-background border border-outline-variant/50 rounded p-stack-sm font-body-sm text-body-sm text-on-surface resize-y outline-none focus:border-secondary" placeholder="Paste your resume text here..." value={resumeText} onChange={(event) => setResumeText(event.target.value)} required />
        </div>
        <div className="bg-surface-container-lowest border border-outline-variant rounded-lg p-stack-md shadow-sm flex flex-col h-full">
          <h2 className="font-label-uppercase text-label-uppercase text-primary mb-stack-sm">Job Description</h2>
          <textarea className="w-full flex-grow min-h-[300px] bg-background border border-outline-variant/50 rounded p-stack-sm font-body-sm text-body-sm text-on-surface resize-y outline-none focus:border-secondary" placeholder="Paste the target job description here..." value={jobDescriptionText} onChange={(event) => setJobDescriptionText(event.target.value)} required />
        </div>
        <div className="lg:col-span-2 flex flex-col items-center gap-3">
          {tool.error && <p className="text-body-sm text-error">{tool.error}</p>}
          <Button size="lg" className="px-10 py-6 h-auto font-headline-md text-headline-md gap-3 rounded-lg shadow-md" disabled={tool.loading}>
            <span className="material-symbols-outlined">troubleshoot</span>
            {tool.loading ? "Checking..." : "Check Resume Match"}
          </Button>
        </div>
      </form>
      <ResultPanel title="Resume Match" result={tool.result} />
    </>
  )
}

export function KeywordScannerTool() {
  const [resumeText, setResumeText] = useState("")
  const [targetRole, setTargetRole] = useState("Software Engineer")
  const tool = useTool<Record<string, unknown>>()

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-gutter">
      <form
        className="bg-surface-container-lowest border border-surface-variant rounded-lg p-stack-lg shadow-sm flex flex-col gap-stack-md"
        onSubmit={(event) => {
          event.preventDefault()
          tool.post("/api/tools/keyword-scan", { resumeText, targetRole })
        }}
      >
        <select className="w-full bg-surface-bright border border-surface-variant rounded py-3 px-4" value={targetRole} onChange={(event) => setTargetRole(event.target.value)}>
          {["Software Engineer", "Java Developer", "Data Analyst", "Business Analyst", "QA Engineer", "DevOps Engineer", "Data Engineer", "Product Manager"].map((role) => (
            <option key={role}>{role}</option>
          ))}
        </select>
        <textarea className="w-full min-h-[300px] bg-surface-bright border border-surface-variant rounded p-4 font-body-sm text-body-sm resize-y outline-none focus:border-secondary" placeholder="Paste your resume text here..." value={resumeText} onChange={(event) => setResumeText(event.target.value)} required />
        {tool.error && <p className="text-body-sm text-error">{tool.error}</p>}
        <Button size="lg" className="px-6 py-3 font-semibold h-auto gap-2" disabled={tool.loading}>
          <span className={`material-symbols-outlined ${tool.loading ? "animate-spin" : ""}`}>{tool.loading ? "refresh" : "radar"}</span>
          {tool.loading ? "Scanning..." : "Scan Resume"}
        </Button>
      </form>
      <ResultPanel title="Keyword Scan" result={tool.result} />
    </div>
  )
}

export function JdKeywordTool() {
  const [jobDescriptionText, setJobDescriptionText] = useState("")
  const tool = useTool<Record<string, unknown>>()

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-gutter w-full">
      <form
        className="col-span-1 lg:col-span-7 bg-surface-container-lowest border border-surface-variant rounded-xl p-stack-lg shadow-sm flex flex-col"
        onSubmit={(event) => {
          event.preventDefault()
          tool.post("/api/tools/jd-keywords", { jobDescriptionText })
        }}
      >
        <textarea className="w-full min-h-[360px] bg-transparent border border-surface-variant rounded-lg focus:ring-0 resize-y p-4 font-body-sm text-body-sm text-on-surface outline-none focus:border-secondary" placeholder="Paste the full job description here..." value={jobDescriptionText} onChange={(event) => setJobDescriptionText(event.target.value)} required />
        {tool.error && <p className="text-body-sm text-error mt-3">{tool.error}</p>}
        <Button size="lg" className="w-full py-3 h-auto font-body-base font-medium gap-2 mt-4" disabled={tool.loading}>
          <span className="material-symbols-outlined">memory</span>
          {tool.loading ? "Extracting..." : "Extract JD Keywords"}
        </Button>
      </form>
      <div className="col-span-1 lg:col-span-5">
        <ResultPanel title="JD Keywords" result={tool.result} />
      </div>
    </div>
  )
}

export function SalaryEstimatorTool() {
  const [role, setRole] = useState("Java Developer")
  const [location, setLocation] = useState("Dallas, TX")
  const [yearsExperience, setYearsExperience] = useState("3-5 Years")
  const [workMode, setWorkMode] = useState("Hybrid")
  const [skills, setSkills] = useState("Java, Spring Boot, Microservices, SQL")
  const tool = useTool<Record<string, unknown>>()

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-gutter items-start">
      <form
        className="lg:col-span-4 bg-surface-container-lowest border border-outline-variant/30 rounded-xl p-stack-lg shadow-sm flex flex-col gap-stack-md"
        onSubmit={(event) => {
          event.preventDefault()
          tool.post("/api/tools/salary-estimate", { role, location, yearsExperience, workMode, skills })
        }}
      >
        <input className="w-full bg-surface-container-lowest border border-outline-variant/50 rounded-md px-3 py-2.5 font-body-sm outline-none focus:border-secondary" value={role} onChange={(event) => setRole(event.target.value)} placeholder="Job title" required />
        <input className="w-full bg-surface-container-lowest border border-outline-variant/50 rounded-md px-3 py-2.5 font-body-sm outline-none focus:border-secondary" value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Location" required />
        <select className="w-full bg-surface-container-lowest border border-outline-variant/50 rounded-md px-3 py-2.5 font-body-sm" value={yearsExperience} onChange={(event) => setYearsExperience(event.target.value)}>
          <option>0-2 Years</option>
          <option>3-5 Years</option>
          <option>6-9 Years</option>
          <option>10+ Years</option>
        </select>
        <select className="w-full bg-surface-container-lowest border border-outline-variant/50 rounded-md px-3 py-2.5 font-body-sm" value={workMode} onChange={(event) => setWorkMode(event.target.value)}>
          <option>On-site</option>
          <option>Hybrid</option>
          <option>Remote</option>
        </select>
        <textarea className="w-full bg-surface-container-lowest border border-outline-variant/50 rounded-md px-3 py-2.5 font-body-sm resize-y outline-none focus:border-secondary" rows={3} value={skills} onChange={(event) => setSkills(event.target.value)} />
        {tool.error && <p className="text-body-sm text-error">{tool.error}</p>}
        <Button className="mt-2 w-full font-label-uppercase text-label-uppercase py-3 gap-2 h-auto" disabled={tool.loading}>
          <span className="material-symbols-outlined text-[18px]">sync</span>
          {tool.loading ? "Calculating..." : "Recalculate Estimate"}
        </Button>
      </form>
      <div className="lg:col-span-8">
        <ResultPanel title="Salary Estimate" result={tool.result} />
      </div>
    </div>
  )
}

export function BulletGeneratorTool() {
  const [jobTitle, setJobTitle] = useState("")
  const [existingBullet, setExistingBullet] = useState("")
  const [toolsUsed, setToolsUsed] = useState("")
  const [impactMetric, setImpactMetric] = useState("")
  const tool = useTool<Record<string, unknown>>()

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-gutter items-start">
      <form
        className="lg:col-span-5 bg-surface-container-lowest border border-outline-variant rounded-xl p-6 shadow-sm"
        onSubmit={(event) => {
          event.preventDefault()
          tool.post("/api/tools/bullet-generator", { jobTitle, existingBullet, toolsUsed, impactMetric })
        }}
      >
        <div className="space-y-6">
          <input className="w-full bg-surface-bright border border-surface-variant rounded-lg px-4 py-3 text-primary outline-none focus:border-secondary" placeholder="Target job title" value={jobTitle} onChange={(event) => setJobTitle(event.target.value)} required />
          <textarea className="w-full bg-surface-bright border border-surface-variant rounded-lg px-4 py-3 text-primary outline-none focus:border-secondary resize-y" placeholder="Existing bullet point" rows={4} value={existingBullet} onChange={(event) => setExistingBullet(event.target.value)} required />
          <input className="w-full bg-surface-bright border border-surface-variant rounded-lg px-4 py-3 text-primary outline-none focus:border-secondary" placeholder="Tools used" value={toolsUsed} onChange={(event) => setToolsUsed(event.target.value)} />
          <input className="w-full bg-surface-bright border border-surface-variant rounded-lg px-4 py-3 text-primary outline-none focus:border-secondary" placeholder="Impact or metric" value={impactMetric} onChange={(event) => setImpactMetric(event.target.value)} />
          {tool.error && <p className="text-body-sm text-error">{tool.error}</p>}
          <Button size="lg" className="w-full py-3 h-auto gap-2" disabled={tool.loading}>
            <span className={`material-symbols-outlined ${tool.loading ? "animate-spin" : ""}`}>{tool.loading ? "refresh" : "auto_fix_high"}</span>
            {tool.loading ? "Generating..." : "Generate Improvements"}
          </Button>
        </div>
      </form>
      <div className="lg:col-span-7">
        <ResultPanel title="Bullet Suggestions" result={tool.result} />
      </div>
    </div>
  )
}

export function SummaryGeneratorTool() {
  const [targetRole, setTargetRole] = useState("")
  const [yearsExperience, setYearsExperience] = useState("")
  const [topSkills, setTopSkills] = useState("")
  const [industry, setIndustry] = useState("")
  const [jobDescription, setJobDescription] = useState("")
  const tool = useTool<Record<string, unknown>>()

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-gutter items-start">
      <form
        className="lg:col-span-5 bg-surface-container-lowest border border-outline-variant rounded-xl p-6 shadow-sm space-y-4"
        onSubmit={(event) => {
          event.preventDefault()
          tool.post("/api/tools/summary-generator", {
            targetRole,
            yearsExperience,
            topSkills,
            industry,
            jobDescription,
          })
        }}
      >
        <input className="w-full bg-surface-bright border border-surface-variant rounded-lg px-4 py-3 outline-none focus:border-secondary" placeholder="Target role" value={targetRole} onChange={(event) => setTargetRole(event.target.value)} required />
        <input className="w-full bg-surface-bright border border-surface-variant rounded-lg px-4 py-3 outline-none focus:border-secondary" placeholder="Years of experience" value={yearsExperience} onChange={(event) => setYearsExperience(event.target.value)} />
        <input className="w-full bg-surface-bright border border-surface-variant rounded-lg px-4 py-3 outline-none focus:border-secondary" placeholder="Top skills" value={topSkills} onChange={(event) => setTopSkills(event.target.value)} required />
        <input className="w-full bg-surface-bright border border-surface-variant rounded-lg px-4 py-3 outline-none focus:border-secondary" placeholder="Industry" value={industry} onChange={(event) => setIndustry(event.target.value)} />
        <textarea className="w-full bg-surface-bright border border-surface-variant rounded-lg px-4 py-3 outline-none focus:border-secondary resize-y" placeholder="Optional job description" rows={4} value={jobDescription} onChange={(event) => setJobDescription(event.target.value)} />
        {tool.error && <p className="text-body-sm text-error">{tool.error}</p>}
        <Button size="lg" className="w-full py-3 h-auto gap-2" disabled={tool.loading}>
          <span className="material-symbols-outlined">subject</span>
          {tool.loading ? "Generating..." : "Generate Summaries"}
        </Button>
      </form>
      <div className="lg:col-span-7">
        <ResultPanel title="Resume Summaries" result={tool.result} />
      </div>
    </div>
  )
}

export function InterviewQuestionsTool() {
  const [jobDescription, setJobDescription] = useState("")
  const [role, setRole] = useState("")
  const [experienceLevel, setExperienceLevel] = useState("")
  const tool = useTool<Record<string, unknown>>()

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-gutter items-start">
      <form
        className="lg:col-span-5 bg-surface-container-lowest border border-outline-variant rounded-xl p-6 shadow-sm space-y-4"
        onSubmit={(event) => {
          event.preventDefault()
          tool.post("/api/tools/interview-questions", { jobDescription, role, experienceLevel })
        }}
      >
        <input className="w-full bg-surface-bright border border-surface-variant rounded-lg px-4 py-3 outline-none focus:border-secondary" placeholder="Role" value={role} onChange={(event) => setRole(event.target.value)} />
        <input className="w-full bg-surface-bright border border-surface-variant rounded-lg px-4 py-3 outline-none focus:border-secondary" placeholder="Experience level" value={experienceLevel} onChange={(event) => setExperienceLevel(event.target.value)} />
        <textarea className="w-full bg-surface-bright border border-surface-variant rounded-lg px-4 py-3 outline-none focus:border-secondary resize-y" placeholder="Paste job description" rows={10} value={jobDescription} onChange={(event) => setJobDescription(event.target.value)} required />
        {tool.error && <p className="text-body-sm text-error">{tool.error}</p>}
        <Button size="lg" className="w-full py-3 h-auto gap-2" disabled={tool.loading}>
          <span className="material-symbols-outlined">quiz</span>
          {tool.loading ? "Generating..." : "Generate Interview Questions"}
        </Button>
      </form>
      <div className="lg:col-span-7">
        <ResultPanel title="Interview Questions" result={tool.result} />
      </div>
    </div>
  )
}
